import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import com.toedter.calendar.JTextFieldDateEditor;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.regex.*;
import javax.swing.JOptionPane;

import java.util.Date;
import javax.swing.JComboBox;
public class AddStaff extends javax.swing.JFrame {

    /**
     * Creates new form AddCustomer
     */
    
    Staff_Data obj ;
    
    
    JTextFieldDateEditor dateEditor = new JTextFieldDateEditor();
    
    public AddStaff() {
        initComponents();
        obj = new Staff_Data();
        
        EditDate();
        
        
         Calendar calendar = Calendar.getInstance();
       // calendar.add(Calendar.DAY_OF_MONTH, 1); 
            
        Date minDate = calendar.getTime();
        jDateChooser1.setMinSelectableDate(minDate);
        
        jLabel7.setVisible(false);
        jLabel8.setVisible(false);
        jLabel14.setVisible(false);
        jLabel17.setVisible(false);
        jLabel15.setVisible(false);
        jLabel16.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ageTxtField = new javax.swing.JTextField();
        genderComboBox = new javax.swing.JComboBox<>();
        addressTxtField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cnicTxtField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        gymTimeComboBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        mobileTxtField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        emainTxtField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        amountTxtField = new javax.swing.JTextField();
        saveBTN = new javax.swing.JButton();
        resetBTN = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        staffTypeComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 65));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(920, 605));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add Customer60.png"))); // NOI18N
        jLabel1.setText("Add Staff");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, -1, 69));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Enter Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, -1));

        nameTxtField.setText("Enter Name");
        nameTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameTxtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameTxtFieldFocusLost(evt);
            }
        });
        nameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTxtFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 220, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Enter Age");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 70, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Mobile No.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Enter Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 370, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Select Gender");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, -1, -1));

        ageTxtField.setText("Enter Age");
        ageTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ageTxtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ageTxtFieldFocusLost(evt);
            }
        });
        ageTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTxtFieldActionPerformed(evt);
            }
        });
        getContentPane().add(ageTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 220, -1));

        genderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Male", "Female", "Other" }));
        genderComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(genderComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 220, -1));

        addressTxtField.setText("Enter Address");
        addressTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressTxtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addressTxtFieldFocusLost(evt);
            }
        });
        addressTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTxtFieldActionPerformed(evt);
            }
        });
        getContentPane().add(addressTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 220, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("CNIC No.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        cnicTxtField.setText("Enter CNIC Number");
        cnicTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cnicTxtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cnicTxtFieldFocusLost(evt);
            }
        });
        cnicTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnicTxtFieldActionPerformed(evt);
            }
        });
        getContentPane().add(cnicTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 220, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Gym Time");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, -1, -1));

        gymTimeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "05:00AM - 09:00AM", "12:00PM - 03:00PM", "05:00PM - 11:00PM" }));
        gymTimeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gymTimeComboBoxActionPerformed(evt);
            }
        });
        getContentPane().add(gymTimeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 220, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Enter Address");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, -1, -1));

        mobileTxtField.setText("Enter Mobile Number");
        mobileTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mobileTxtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mobileTxtFieldFocusLost(evt);
            }
        });
        mobileTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileTxtFieldActionPerformed(evt);
            }
        });
        getContentPane().add(mobileTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 220, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Enter Salary");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, -1, -1));

        emainTxtField.setText("Enter Email Address");
        emainTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emainTxtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emainTxtFieldFocusLost(evt);
            }
        });
        emainTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emainTxtFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emainTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 220, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Enter Date");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, -1, -1));

        amountTxtField.setText("Enter Amount");
        amountTxtField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                amountTxtFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                amountTxtFieldFocusLost(evt);
            }
        });
        amountTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTxtFieldActionPerformed(evt);
            }
        });
        getContentPane().add(amountTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, 220, -1));

        saveBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        saveBTN.setForeground(new java.awt.Color(51, 51, 51));
        saveBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        saveBTN.setText("Save");
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });
        getContentPane().add(saveBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 220, -1));

        resetBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        resetBTN.setForeground(new java.awt.Color(51, 51, 51));
        resetBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset.png"))); // NOI18N
        resetBTN.setText("Reset");
        resetBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBTNActionPerformed(evt);
            }
        });
        getContentPane().add(resetBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 540, 220, -1));

        jDateChooser1.setDateFormatString("dd/MM/yyyy");
        jDateChooser1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jDateChooser1FocusGained(evt);
            }
        });
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 180, 220, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 51));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Wrong Password 2.png"))); // NOI18N
        jLabel7.setText("Invalid CNlC 13-Digits");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 51));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Wrong Password 2.png"))); // NOI18N
        jLabel8.setText("Invalid Age  <8<120");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 51, 51));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Wrong Password 2.png"))); // NOI18N
        jLabel14.setText("Invalid Address  XX12, 12XX");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 51, 51));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Wrong Password 2.png"))); // NOI18N
        jLabel15.setText("Invalid Email  abc@gmail.com");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 51, 51));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Wrong Password 2.png"))); // NOI18N
        jLabel16.setText("Invalid Mobile No. 11-Digits ");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, -1, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 51, 51));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Wrong Password 2.png"))); // NOI18N
        jLabel17.setText("Invalid Amount Digits");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 460, -1, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Staff Type");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        staffTypeComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Trainer", "Helper", "Worker" }));
        staffTypeComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffTypeComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(staffTypeComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 220, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTxtFieldActionPerformed

    private void genderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderComboBoxActionPerformed

    private void addressTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTxtFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_addressTxtFieldActionPerformed

    private void gymTimeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gymTimeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gymTimeComboBoxActionPerformed

    private void mobileTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileTxtFieldActionPerformed

    private void emainTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emainTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emainTxtFieldActionPerformed
    public static boolean vallidCNIC(String str){
        String cnicPattern = "^\\d{13}$";
        Pattern pt = Pattern.compile(cnicPattern);
        Matcher matcher = pt.matcher(str);
        return matcher.matches();
    }
    public static boolean ValidAge(String age){
        if(age.matches("\\d{3}") || age.matches("\\d{2}") || age.matches("\\d{1}"))
        {
           int n = Integer.parseInt(age);
            if(n > 8 || n <= 120 ){
                return true;
            }
        }
            
            return false;
    }
      public static boolean validAddress(String str){
        String cnicPattern = "^(?=.*[a-zA-Z])[a-zA-Z0-9,.\\s]+$";
        Pattern pt = Pattern.compile(cnicPattern);
        Matcher matcher = pt.matcher(str);
        return matcher.matches();
    }
      public static boolean vallidMobileNo(String str){
        String MobileNoPattern = "^\\d{11}$";
        Pattern pt = Pattern.compile(MobileNoPattern);
        Matcher matcher = pt.matcher(str);
        return matcher.matches();
    }
      public static boolean isValidEmail(String email) {
        String emailPattern = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";
        Pattern pattern = Pattern.compile(emailPattern);

        Matcher matcher = pattern.matcher(email);

        return matcher.matches();
    }
    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
        // TODO add your handling code here:
        if(staffTypeComboBox1.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Please Select Staff Type!", "Complete the form", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(cnicTxtField.getText().equals("Enter CNIC Number") || cnicTxtField.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Enter CNIC Number!", "Complete the form", JOptionPane.INFORMATION_MESSAGE);
        }
         
        else if(!(vallidCNIC(cnicTxtField.getText()))){
            jLabel7.setVisible(true);
            
        }
       else if(nameTxtField.getText().equals("Enter Name") || nameTxtField.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Enter Name!", "Complete the form", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(ageTxtField.getText().equals("Enter Age") || ageTxtField.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Enter Age!", "Complete the form", JOptionPane.INFORMATION_MESSAGE);
        }
      //  else if(!(ValidAge(ageTxtField.getText()))){
        //    jLabel8.setVisible(true);
        //}
        else if(genderComboBox.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Please Select Gender!", "Complete the form", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(addressTxtField.getText().equals("Enter Address") || addressTxtField.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Enter Address!", "Complete the form", JOptionPane.INFORMATION_MESSAGE);
        }
        else if (!(validAddress(addressTxtField.getText()))){
            jLabel14.setVisible(true);
        }
        else if(gymTimeComboBox.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Please Select Gym Time!", "Complete the form", JOptionPane.INFORMATION_MESSAGE);
        }
         
        else if(mobileTxtField.getText().equals("Enter Mobile Number") || mobileTxtField.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Enter Mobile Number!", "Complete the form", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(!(vallidMobileNo(mobileTxtField.getText()))){
            jLabel16.setVisible(true);
        }
        else if(emainTxtField.getText().equals("Enter Email Address") || emainTxtField.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Enter Email Address!", "Complete the form", JOptionPane.INFORMATION_MESSAGE);
        }
        else if(!(isValidEmail(emainTxtField.getText()))){
            jLabel15.setVisible(true);
        }
        else if(amountTxtField.getText().equals("Enter Amount") || amountTxtField.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please Enter Amount!", "Complete the form", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            
            String sCNIC = cnicTxtField.getText();
            String sType = staffTypeComboBox1.getItemAt(staffTypeComboBox1.getSelectedIndex());
            String sName = nameTxtField.getText();
            String sAge = ageTxtField.getText();
            String sGender = genderComboBox.getItemAt(genderComboBox.getSelectedIndex());
            String sAddress = addressTxtField.getText();
            String sDate = String.valueOf(DateFormat(jDateChooser1.getDate())); 
            String sGymTime = gymTimeComboBox.getItemAt(gymTimeComboBox.getSelectedIndex());
            String sMobileNo = mobileTxtField.getText();
            String sEmail = emainTxtField.getText();
            String sAmount = amountTxtField.getText();
            
            // obj object of customer data
            obj.AddStaffDetails(sCNIC,sType, sName, sAge, sGender, sAddress, sDate, sGymTime, sMobileNo, sEmail, sAmount);
            
            
            
            
            new AddStaff().setVisible(true);
        }
    }//GEN-LAST:event_saveBTNActionPerformed

    private void nameTxtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTxtFieldFocusGained
        // TODO add your handling code here:
        if(nameTxtField.getText().equals("Enter Name")){
            nameTxtField.setText("");
        }
    }//GEN-LAST:event_nameTxtFieldFocusGained

    private void ageTxtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageTxtFieldFocusGained
        // TODO add your handling code here:
        jLabel8.setVisible(false);
        if(ageTxtField.getText().equals("Enter Age")){
            ageTxtField.setText("");
        }
    }//GEN-LAST:event_ageTxtFieldFocusGained

    private void addressTxtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressTxtFieldFocusGained
        // TODO add your handling code here:
        jLabel14.setVisible(false);
        if(addressTxtField.getText().equals("Enter Address")){
            addressTxtField.setText("");
        }
    }//GEN-LAST:event_addressTxtFieldFocusGained

    private void cnicTxtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnicTxtFieldFocusGained
        // TODO add your handling code here:
        jLabel7.setVisible(false);
        if(cnicTxtField.getText().equals("Enter CNIC Number")){
            cnicTxtField.setText("");
        }
    }//GEN-LAST:event_cnicTxtFieldFocusGained

    private void mobileTxtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mobileTxtFieldFocusGained
        // TODO add your handling code here:
        jLabel16.setVisible(false);
        if(mobileTxtField.getText().equals("Enter Mobile Number")){
            mobileTxtField.setText("");
        }
    }//GEN-LAST:event_mobileTxtFieldFocusGained

    private void emainTxtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emainTxtFieldFocusGained
        // TODO add your handling code here:
        jLabel15.setVisible(false);
        if(emainTxtField.getText().equals("Enter Email Address")){
            emainTxtField.setText("");
        }
    }//GEN-LAST:event_emainTxtFieldFocusGained

    private void amountTxtFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amountTxtFieldFocusGained
        // TODO add your handling code here:
        if(amountTxtField.getText().equals("Enter Amount")){
            amountTxtField.setText("");
        }
    }//GEN-LAST:event_amountTxtFieldFocusGained

    private void nameTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameTxtFieldFocusLost
        // TODO add your handling code here:
        if(nameTxtField.getText().equals("")){
            nameTxtField.setText("Enter Name");
        }
    }//GEN-LAST:event_nameTxtFieldFocusLost

    private void ageTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageTxtFieldFocusLost
        // TODO add your handling code here:
         if(ageTxtField.getText().equals("")){
            ageTxtField.setText("Enter Age");
        }
    }//GEN-LAST:event_ageTxtFieldFocusLost

    private void addressTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressTxtFieldFocusLost
        // TODO add your handling code here:
         if(addressTxtField.getText().equals("")){
            addressTxtField.setText("Enter Address");
        }
    }//GEN-LAST:event_addressTxtFieldFocusLost

    private void cnicTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnicTxtFieldFocusLost
        // TODO add your handling code here:
         if(cnicTxtField.getText().equals("")){
            cnicTxtField.setText("Enter CNIC Number");
        }
    }//GEN-LAST:event_cnicTxtFieldFocusLost

    private void mobileTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mobileTxtFieldFocusLost
        // TODO add your handling code here:
         if(mobileTxtField.getText().equals("")){
            mobileTxtField.setText("Enter Mobile Number");
        }
    }//GEN-LAST:event_mobileTxtFieldFocusLost

    private void emainTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emainTxtFieldFocusLost
        // TODO add your handling code here:
         if(emainTxtField.getText().equals("")){
            emainTxtField.setText("Enter Email Address");
        }
    }//GEN-LAST:event_emainTxtFieldFocusLost

    private void amountTxtFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amountTxtFieldFocusLost
        // TODO add your handling code here:
        if(amountTxtField.getText().equals("")){
            amountTxtField.setText("Enter Amount");
        }
    }//GEN-LAST:event_amountTxtFieldFocusLost

    private void resetBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBTNActionPerformed
        // TODO add your handling code here:
        nameTxtField.setText("Enter Name");
        ageTxtField.setText("Enter Age");
       
        addressTxtField.setText("Enter Address");
        cnicTxtField.setText("Enter CNIC Number");
        mobileTxtField.setText("Enter Mobile Number");
        emainTxtField.setText("Enter Email Address");
        amountTxtField.setText("Enter Amount");
    }//GEN-LAST:event_resetBTNActionPerformed

    private void amountTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTxtFieldActionPerformed

    private void jDateChooser1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jDateChooser1FocusGained
        // TODO add your handling code here:
        jDateChooser1.show();
    }//GEN-LAST:event_jDateChooser1FocusGained

    private void ageTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTxtFieldActionPerformed

    private void cnicTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnicTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnicTxtFieldActionPerformed

    private void staffTypeComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffTypeComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffTypeComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCustomer().setVisible(true);
            }
        });
    }
            public void EditDate(){
                dateEditor = (JTextFieldDateEditor) jDateChooser1.getDateEditor();
                dateEditor.setEditable(false);
            }
            
            private String DateFormat( Date dt ){
                SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
                
                try {
                   return format.format(dt);
                } catch (Exception e) {
                    System.err.println("Error"+ e.getMessage());
                    return "";
                }
                
            }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTxtField;
    private javax.swing.JTextField ageTxtField;
    private javax.swing.JTextField amountTxtField;
    private javax.swing.JTextField cnicTxtField;
    private javax.swing.JTextField emainTxtField;
    private javax.swing.JComboBox<String> genderComboBox;
    private javax.swing.JComboBox<String> gymTimeComboBox;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mobileTxtField;
    private javax.swing.JTextField nameTxtField;
    private javax.swing.JButton resetBTN;
    private javax.swing.JButton saveBTN;
    private javax.swing.JComboBox<String> staffTypeComboBox1;
    // End of variables declaration//GEN-END:variables
}
