/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Ahmad
 */
public class S_Management extends javax.swing.JFrame {

    /**
     * Creates new form C_Management
     */
    public S_Management() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addCustomerBTN = new javax.swing.JButton();
        listOfCustomersBTN = new javax.swing.JButton();
        updateAndDeleteBTN = new javax.swing.JButton();
        paymentsBTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(197, 65));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1150, 605));

        addCustomerBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add Customer.png"))); // NOI18N
        addCustomerBTN.setText("  Add Staff");
        addCustomerBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCustomerBTNMouseClicked(evt);
            }
        });
        addCustomerBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCustomerBTNActionPerformed(evt);
            }
        });

        listOfCustomersBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/List Of Customers.png"))); // NOI18N
        listOfCustomersBTN.setText("List of Staff");
        listOfCustomersBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listOfCustomersBTNActionPerformed(evt);
            }
        });

        updateAndDeleteBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Update .png"))); // NOI18N
        updateAndDeleteBTN.setText("Update & Delete  ");
        updateAndDeleteBTN.setPreferredSize(new java.awt.Dimension(125, 39));
        updateAndDeleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAndDeleteBTNActionPerformed(evt);
            }
        });

        paymentsBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/payment.png"))); // NOI18N
        paymentsBTN.setText("     Payments     ");
        paymentsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentsBTNActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Stencil", 1, 70)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Staff Management");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(addCustomerBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addComponent(listOfCustomersBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(378, 378, 378)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(paymentsBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(updateAndDeleteBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(2, 2, 2)))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(addCustomerBTN)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(listOfCustomersBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateAndDeleteBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(paymentsBTN)
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addCustomerBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCustomerBTNMouseClicked
        // TODO add your handling code here:
        System.out.println("noww");
    }//GEN-LAST:event_addCustomerBTNMouseClicked

    private void addCustomerBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCustomerBTNActionPerformed
        // TODO add your handling code here:

        new ListOfCustomers().dispose();
        new C_UpdateAndDelete().dispose();
        new C_Payments().dispose();
        new EditAccount().dispose();
        new About().dispose();
        new AddStaff().setVisible(true);
    }//GEN-LAST:event_addCustomerBTNActionPerformed

    private void listOfCustomersBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listOfCustomersBTNActionPerformed
        // TODO add your handling code here:
        new AddCustomer().dispose();
        new C_UpdateAndDelete().dispose();
        new C_Payments().dispose();
        new EditAccount().dispose();
        new About().dispose();

        new ListOfStaff().setVisible(true);
    }//GEN-LAST:event_listOfCustomersBTNActionPerformed

    private void updateAndDeleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAndDeleteBTNActionPerformed
        // TODO add your handling code here:
        new AddCustomer().dispose();
        new ListOfCustomers().dispose();
        new C_Payments().dispose();
        new EditAccount().dispose();
        new About().dispose();
        new S_UpdateAndDelete().setVisible(true);
    }//GEN-LAST:event_updateAndDeleteBTNActionPerformed

    private void paymentsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentsBTNActionPerformed
        // TODO add your handling code here:
        new AddCustomer().dispose();
        new ListOfCustomers().dispose();
        new C_UpdateAndDelete().dispose();
        new EditAccount().dispose();
        new About().dispose();
        new S_Payments().setVisible(true);
    }//GEN-LAST:event_paymentsBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(C_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(C_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(C_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(C_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new C_Management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCustomerBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton listOfCustomersBTN;
    private javax.swing.JButton paymentsBTN;
    private javax.swing.JButton updateAndDeleteBTN;
    // End of variables declaration//GEN-END:variables
}
