
import java.sql.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Abubakar Raza
 */
public class S_UpdateAndDelete extends javax.swing.JFrame {

    /**
     * Creates new form C_UpdateAndDelete
     */
    Staff_Data sData;
    
    
    public S_UpdateAndDelete() {
        initComponents();
         sData = new Staff_Data();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        addressField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ageFIeld = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cnicField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        mobileNoField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        amountField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        genderFIeld = new javax.swing.JTextField();
        gymTimeField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        updateBTN = new javax.swing.JButton();
        resetBTN = new javax.swing.JButton();
        deleteBTN = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        staffTypeField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 65));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Update60 .png"))); // NOI18N
        jLabel1.setText("Update & Delet Staff");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, -1, -1));

        searchButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        searchButton.setText("Search");
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        getContentPane().add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        addressField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                addressFieldFocusLost(evt);
            }
        });
        addressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressFieldActionPerformed(evt);
            }
        });
        getContentPane().add(addressField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 220, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        nameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFieldFocusLost(evt);
            }
        });
        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 220, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Address");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, 22));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("    Age  ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 53, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Gender");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        ageFIeld.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ageFIeldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                ageFIeldFocusLost(evt);
            }
        });
        ageFIeld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageFIeldActionPerformed(evt);
            }
        });
        getContentPane().add(ageFIeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 220, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("CNIC No.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        cnicField.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cnicField.setForeground(new java.awt.Color(255, 0, 51));
        cnicField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cnicFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cnicFieldFocusLost(evt);
            }
        });
        getContentPane().add(cnicField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 111, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Gym Time");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, -1, -1));

        mobileNoField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mobileNoFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mobileNoFieldFocusLost(evt);
            }
        });
        mobileNoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileNoFieldActionPerformed(evt);
            }
        });
        getContentPane().add(mobileNoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 220, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Enter Amount");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, -1, -1));

        emailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailFieldFocusLost(evt);
            }
        });
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, 220, -1));

        amountField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                amountFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                amountFieldFocusLost(evt);
            }
        });
        amountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountFieldActionPerformed(evt);
            }
        });
        getContentPane().add(amountField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, 220, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Mobile No.");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 380, -1, -1));

        genderFIeld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderFIeldActionPerformed(evt);
            }
        });
        getContentPane().add(genderFIeld, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 220, -1));

        gymTimeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gymTimeFieldActionPerformed(evt);
            }
        });
        getContentPane().add(gymTimeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 220, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Enter Date");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, -1, -1));

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 220, -1));

        updateBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateBTN.setForeground(new java.awt.Color(51, 51, 51));
        updateBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/save.png"))); // NOI18N
        updateBTN.setText("Update");
        updateBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBTNActionPerformed(evt);
            }
        });
        getContentPane().add(updateBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 150, -1));

        resetBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        resetBTN.setForeground(new java.awt.Color(51, 51, 51));
        resetBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/reset.png"))); // NOI18N
        resetBTN.setText("Reset");
        resetBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBTNActionPerformed(evt);
            }
        });
        getContentPane().add(resetBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 530, 141, -1));

        deleteBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deleteBTN.setForeground(new java.awt.Color(51, 51, 51));
        deleteBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        deleteBTN.setText("Delete");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, 148, -1));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Staff Type");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));
        getContentPane().add(staffTypeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 220, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
     public static boolean vallidCNIC(String str){
        String cnicPattern = "^\\d{13}$";
        Pattern pt = Pattern.compile(cnicPattern);
        Matcher matcher = pt.matcher(str);
        return matcher.matches();
    }
     public static boolean ValidAge(String age){
        if(age.matches("\\d{3}"))
        {
           int n = Integer.parseInt(age);
            if(n < 8 || n > 120 ){
                return false;
            }
        }
            
            return true;
    }
     public static boolean validAddress(String str){
        String cnicPattern = "^(?=.*[a-zA-Z])[a-zA-Z0-9,.\\s]+$";
        Pattern pt = Pattern.compile(cnicPattern);
        Matcher matcher = pt.matcher(str);
        return matcher.matches();
    }
     public static boolean vallidMobileNo(String str){
        String MobileNoPattern = "^\\d{13}$";
        Pattern pt = Pattern.compile(MobileNoPattern);
        Matcher matcher = pt.matcher(str);
        return matcher.matches();
    }
      public static boolean isValidEmail(String email) {
        // Regular expression for a valid email pattern
        String emailPattern = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$";

        // Compile the pattern
        Pattern pattern = Pattern.compile(emailPattern);

        // Match the input email against the pattern
        Matcher matcher = pattern.matcher(email);

        // Return true if the email matches the pattern, otherwise return false
        return matcher.matches();
    }
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
      
        String sCNIC = cnicField.getText();
        try {
            Connection con = DriverManager.getConnection("jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=gym_management_system;encrypt=true;trustServerCertificate=true","admin","12345");
            Statement st = con.createStatement();
            String qry = "SELECT * FROM Staff_data WHERE CNIC = '"+sCNIC+"'";
            ResultSet rs = st.executeQuery(qry);
            if(rs.next()){
          //  while(rs.next()){
                staffTypeField.setText(rs.getString(2));
                nameField.setText(rs.getString(3));
                ageFIeld.setText(rs.getString(4));
                genderFIeld.setText(rs.getString(5));
                genderFIeld.setEditable(false);
                addressField.setText(rs.getString(6));
                jTextField6.setText(rs.getString(7));
                jTextField6.setEditable(false);
                gymTimeField.setText(rs.getString(8));
                mobileNoField.setText(rs.getString(9));
                emailField.setText(rs.getString(10));
                amountField.setText(rs.getString(11));
         //   }
            }else{
                JOptionPane.showMessageDialog(null, "Not Found");
            }
        } catch (Exception e) {
            System.err.println(e.getMessage());
            
        }
        
       
    }//GEN-LAST:event_searchButtonActionPerformed
    
    private void addressFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFieldFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_addressFieldFocusGained

    private void addressFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFieldFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_addressFieldFocusLost

    private void addressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_addressFieldActionPerformed

    private void nameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFieldFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nameFieldFocusGained

    private void nameFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFieldFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_nameFieldFocusLost

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFieldActionPerformed

    private void ageFIeldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageFIeldFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ageFIeldFocusGained

    private void ageFIeldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageFIeldFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ageFIeldFocusLost

    private void cnicFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnicFieldFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cnicFieldFocusGained

    private void cnicFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cnicFieldFocusLost
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cnicFieldFocusLost

    private void mobileNoFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mobileNoFieldFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mobileNoFieldFocusGained

    private void mobileNoFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mobileNoFieldFocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_mobileNoFieldFocusLost

    private void mobileNoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileNoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileNoFieldActionPerformed

    private void emailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusGained
        // TODO add your handling code here:
        
    }//GEN-LAST:event_emailFieldFocusGained

    private void emailFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailFieldFocusLost
        // TODO add your handling code here:
       
    }//GEN-LAST:event_emailFieldFocusLost

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void amountFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amountFieldFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_amountFieldFocusGained

    private void amountFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_amountFieldFocusLost
        // TODO add your handling code here:
      
    }//GEN-LAST:event_amountFieldFocusLost

    private void genderFIeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderFIeldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderFIeldActionPerformed

    private void ageFIeldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageFIeldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageFIeldActionPerformed

    private void gymTimeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gymTimeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gymTimeFieldActionPerformed

    private void amountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountFieldActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void updateBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBTNActionPerformed
        // TODO add your handling code here:
               String cCNIC = cnicField.getText();
               String sType = staffTypeField.getText();
               String cName = nameField.getText();
               String cAge = ageFIeld.getText();
               String cGender = genderFIeld.getText();
               String cAddress = addressField.getText();
               String cDate = jTextField6.getText();
               String cGymTime = gymTimeField.getText();
               String cMobileNo = mobileNoField.getText();
               String cEmail = emailField.getText();
               String cAmount = amountField.getText();
               
               sData.UpdateStaffDetails(cCNIC,sType, cName, cAge, cGender, cAddress, cDate, cGymTime, cMobileNo, cEmail, cAmount);
        
        
        new S_UpdateAndDelete().setVisible(true);
    }//GEN-LAST:event_updateBTNActionPerformed

    private void resetBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBTNActionPerformed
        // TODO add your handling code here:
        new S_UpdateAndDelete().setVisible(true);
        
    }//GEN-LAST:event_resetBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        // TODO add your handling code here:
        String cCNIC = cnicField.getText();
        sData.DeleteStaffDetails(cCNIC);
        
        new S_UpdateAndDelete().setVisible(true);
    }//GEN-LAST:event_deleteBTNActionPerformed

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_searchButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(C_UpdateAndDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(C_UpdateAndDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(C_UpdateAndDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(C_UpdateAndDelete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new S_UpdateAndDelete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JTextField ageFIeld;
    private javax.swing.JTextField amountField;
    private javax.swing.JTextField cnicField;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField genderFIeld;
    private javax.swing.JTextField gymTimeField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField mobileNoField;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton resetBTN;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField staffTypeField;
    private javax.swing.JButton updateBTN;
    // End of variables declaration//GEN-END:variables

    void getData(String[] listOfCustomers) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
